version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    hostname: redis
    volumes:
      - 'redis:/var/lib/redis/data'

  celery-file-storage-worker:
    build:
      context: celery-workers
      dockerfile: Dockerfile.fs
    command: sh run-file-storage-worker.sh
    volumes:
      - ./data:/home/data
    depends_on:
      - redis
      - hadoop
    links:
      - redis
      - hadoop

  celery-executor-worker:
    build:
      context: celery-workers
      dockerfile: Dockerfile.exec
    command: sh run-executor-worker.sh
    volumes:
      - ./data:/home/data
    depends_on:
      - redis
      - hadoop
    links:
      - redis
      - hadoop

  kmeans-swagger-svc:
    build:
      context: .
      dockerfile: Dockerfile.kmeans_svc
    depends_on:
      - celery-executor-worker
      - celery-file-storage-worker
      - redis
    links:
      - celery-executor-worker
      - celery-file-storage-worker
      - redis

  nodejs-file-server:
    build:
      context: file-server
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - '3333:3333'
    links:
      - kmeans-swagger-svc
    depends_on:
      - kmeans-swagger-svc

  hadoop:
    image: 'harisekhon/hadoop:2.7'

volumes:
  redis:
