swagger: '2.0'
info:
  description: 'TV Shows, Movies and Music News'
  version: 1.0.0
  title: Entertainment Tweetly
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: sossen@iu.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:9550'
basePath: /cloudmesh/stream
schemes:
  - http
paths:
  '/music/{artistName}':
    get:
      tags:
        - Music
      summary: Find latest tweets related to an artist
      consumes:
        - application/json
      produces:
        - application/json
      description: Returns latest tweets related to an artist
      operationId: getMusicTweetsByArtist
      parameters:
        - name: artistName
          in: path
          description: Name of Artist
          required: true
          type: string
          minLength: 3
          maxLength: 20
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Music'
        '400':
          description: Invalid name given
          schema:
            type: string
        default:
          description: Unexpected error occurred
          schema:
            $ref: '#/definitions/Error'
  '/movies/{movieTitle}':
    get:
      tags:
        - Movies
      summary: Find latest tweets related to a movie
      consumes:
        - application/json
      produces:
        - application/json
      description: Returns latest tweets related to a movie
      operationId: getMovieTweetsByTitle
      parameters:
        - name: movieTitle
          in: path
          description: Title of Movie
          required: true
          type: string
          minLength: 3
          maxLength: 20
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Movie'
        '400':
          description: Invalid title given
          schema:
            type: string
        default:
          description: Unexpected error occurred
          schema:
            $ref: '#/definitions/Error'
  '/TVShow/{showTitle}':
    get:
      tags:
        - TV Shows
      summary: Find TV Show by Title
      consumes:
        - application/json
      produces:
        - application/json
      description: Returns latest tweets related to TV show
      operationId: getTVShowTweetsByTitle
      parameters:
        - name: showTitle
          in: path
          description: Title of Show
          required: true
          type: string
          minLength: 3
          maxLength: 20
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/TVShow'
        '400':
          description: Invalid title given
          schema:
            type: string
        default:
          description: Unexpected error occurred
          schema:
            $ref: '#/definitions/Error'
definitions:
  Music:
    type: object
    properties:
      name: 
        type: string
      tweets:
        type: array
        items:
          $ref: '#/definitions/Tweet'
  Movie:
    type: object
    properties:
      name: 
        type: string
      tweets:
        type: array
        items:
          $ref: '#/definitions/Tweet'
  TVShow:
    type: object
    properties:
      name: 
        type: string
      tweets:
        type: array
        items:
          $ref: '#/definitions/Tweet'
  Tweet:
    type: object
    required:
      - id
      - user
      - tweet
      - created_at
    properties:
      id:
        type: integer
        format: int64
      user:
        type: string
      tweet:
        type: string
      is_retweet:
        type: boolean
      retweets_for_original:
        type: integer
        format: int64
      likes_for_original:
        type: integer
        format: int64
      created_at:
        type: string
      official:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
